// Scans the Vite build output (dist/) and generates
// server/embeddedAssets.generated.ts: a module of `with { type: "file" }`
// imports plus a URL-path -> embedded-path map. `bun build --compile` bakes the
// imported files into the binary so the frontend is served from memory instead
// of from process.cwd()/dist at runtime.
import { readdir } from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dir, "..");
const distDir = path.join(repoRoot, "dist");
const outFile = path.join(repoRoot, "server", "embeddedAssets.generated.ts");

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

const distIndex = Bun.file(path.join(distDir, "index.html"));
if (!(await distIndex.exists())) {
  console.error(
    `dist/index.html not found at ${distDir}. Run \`bun run build\` first.`,
  );
  process.exit(1);
}

const files = (await walk(distDir)).sort();

const importLines: string[] = [];
const mapLines: string[] = [];
files.forEach((abs, i) => {
  // Import path relative to server/ (where the generated file lives).
  const importPath = `../${path.relative(repoRoot, abs).split(path.sep).join("/")}`;
  // Web path relative to dist root, POSIX separators, leading slash.
  const webPath = `/${path.relative(distDir, abs).split(path.sep).join("/")}`;
  importLines.push(
    `import a${i} from ${JSON.stringify(importPath)} with { type: "file" };`,
  );
  mapLines.push(`  [${JSON.stringify(webPath)}, a${i}],`);
});

const contents = `// @ts-nocheck
// AUTO-GENERATED by scripts/gen-embedded-assets.ts — do not edit.
${importLines.join("\n")}

export const embeddedAssets = new Map<string, string>([
${mapLines.join("\n")}
]);
`;

await Bun.write(outFile, contents);
console.log(
  `Embedded ${files.length} asset(s) -> ${path.relative(repoRoot, outFile)}`,
);
